name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y rpm

      - name: Build binutils rpm
        run: |
          sudo mkdir /usr/src/SOURCES
          rmpbuild -ba "binutils2.42.spec"
