name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y rpm

      - name: Build binutils rpm
        run: |
          sudo mkdir /usr/src/SOURCES
          cd /usr/src/SOURCES
          sudo wget -q https://ftp.gnu.org/gnu/binutils/binutils-2.42.tar.gz
          cd $GITHUB_WORKSPACE
          sudo rpmbuild -ba "binutils2.42.spec"
